package entityRepository;

public enum Subject {
    //PRIMER AÑO
    PRACTICAS_PROFESIONALIZANTES_I,
    ARQUITECTURA_DE_COMPUTADORAS,
    ALGEBRA,
    CIENCIA_TECNOLOGIA_SOCIEDAD,
    SISTEMAS_ORGANIZACIONES,
    INGLES_I,
    ALGORITMOS_ESTRUCTURAS_DE_DATOS_I,
    ANALISIS_MATEMATICO_I,

    //SEGUNDO AÑO
    PRACTICAS_PROFESIONALIZANTES_II,
    SISTEMAS_OPERATIVOS,
    ESTADISTICA,
    ALGORITMOS_ESTRUCTURAS_DE_DATOS_II,
    INGLES_II,
    ANALISIS_MATEMATICO_II,
    BASES_DE_DATOS,
    INGENIERIA_DE_SOFTWARE_I,

    //TERCER AÑO
    PRACTICAS_PROFESIONALIZANTES_III,
    SEMINARIO_DE_ACTUALIZACION,
    ASPECTOS_LEGALES_DE_LA_PROFESION,
    REDES_Y_COMUNICACIONES,
    ALGORITMOS_ESTRUCTURAS_DE_DATOS_III,
    INGENIERIA_DE_SOFTWARE_II,
    INGLES_III
}
